
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DropPoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DropPoint
 * 
 */
export type DropPointModel = runtime.Types.Result.DefaultSelection<Prisma.$DropPointPayload>

export type AggregateDropPoint = {
  _count: DropPointCountAggregateOutputType | null
  _avg: DropPointAvgAggregateOutputType | null
  _sum: DropPointSumAggregateOutputType | null
  _min: DropPointMinAggregateOutputType | null
  _max: DropPointMaxAggregateOutputType | null
}

export type DropPointAvgAggregateOutputType = {
  latitude: number | null
  longitude: number | null
}

export type DropPointSumAggregateOutputType = {
  latitude: number | null
  longitude: number | null
}

export type DropPointMinAggregateOutputType = {
  id: string | null
  name: string | null
  code: string | null
  province: string | null
  city: string | null
  district: string | null
  address: string | null
  latitude: number | null
  longitude: number | null
  contactPerson: string | null
  contactPhone: string | null
  workingHours: string | null
  type: string | null
  description: string | null
  isActive: boolean | null
  createdBy: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DropPointMaxAggregateOutputType = {
  id: string | null
  name: string | null
  code: string | null
  province: string | null
  city: string | null
  district: string | null
  address: string | null
  latitude: number | null
  longitude: number | null
  contactPerson: string | null
  contactPhone: string | null
  workingHours: string | null
  type: string | null
  description: string | null
  isActive: boolean | null
  createdBy: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type DropPointCountAggregateOutputType = {
  id: number
  name: number
  code: number
  province: number
  city: number
  district: number
  address: number
  latitude: number
  longitude: number
  contactPerson: number
  contactPhone: number
  workingHours: number
  type: number
  description: number
  isActive: number
  createdBy: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type DropPointAvgAggregateInputType = {
  latitude?: true
  longitude?: true
}

export type DropPointSumAggregateInputType = {
  latitude?: true
  longitude?: true
}

export type DropPointMinAggregateInputType = {
  id?: true
  name?: true
  code?: true
  province?: true
  city?: true
  district?: true
  address?: true
  latitude?: true
  longitude?: true
  contactPerson?: true
  contactPhone?: true
  workingHours?: true
  type?: true
  description?: true
  isActive?: true
  createdBy?: true
  createdAt?: true
  updatedAt?: true
}

export type DropPointMaxAggregateInputType = {
  id?: true
  name?: true
  code?: true
  province?: true
  city?: true
  district?: true
  address?: true
  latitude?: true
  longitude?: true
  contactPerson?: true
  contactPhone?: true
  workingHours?: true
  type?: true
  description?: true
  isActive?: true
  createdBy?: true
  createdAt?: true
  updatedAt?: true
}

export type DropPointCountAggregateInputType = {
  id?: true
  name?: true
  code?: true
  province?: true
  city?: true
  district?: true
  address?: true
  latitude?: true
  longitude?: true
  contactPerson?: true
  contactPhone?: true
  workingHours?: true
  type?: true
  description?: true
  isActive?: true
  createdBy?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type DropPointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DropPoint to aggregate.
   */
  where?: Prisma.DropPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DropPoints to fetch.
   */
  orderBy?: Prisma.DropPointOrderByWithRelationInput | Prisma.DropPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DropPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DropPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DropPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DropPoints
  **/
  _count?: true | DropPointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DropPointAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DropPointSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DropPointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DropPointMaxAggregateInputType
}

export type GetDropPointAggregateType<T extends DropPointAggregateArgs> = {
      [P in keyof T & keyof AggregateDropPoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDropPoint[P]>
    : Prisma.GetScalarType<T[P], AggregateDropPoint[P]>
}




export type DropPointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DropPointWhereInput
  orderBy?: Prisma.DropPointOrderByWithAggregationInput | Prisma.DropPointOrderByWithAggregationInput[]
  by: Prisma.DropPointScalarFieldEnum[] | Prisma.DropPointScalarFieldEnum
  having?: Prisma.DropPointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DropPointCountAggregateInputType | true
  _avg?: DropPointAvgAggregateInputType
  _sum?: DropPointSumAggregateInputType
  _min?: DropPointMinAggregateInputType
  _max?: DropPointMaxAggregateInputType
}

export type DropPointGroupByOutputType = {
  id: string
  name: string
  code: string | null
  province: string | null
  city: string | null
  district: string | null
  address: string | null
  latitude: number | null
  longitude: number | null
  contactPerson: string | null
  contactPhone: string | null
  workingHours: string | null
  type: string | null
  description: string | null
  isActive: boolean
  createdBy: string
  createdAt: Date
  updatedAt: Date
  _count: DropPointCountAggregateOutputType | null
  _avg: DropPointAvgAggregateOutputType | null
  _sum: DropPointSumAggregateOutputType | null
  _min: DropPointMinAggregateOutputType | null
  _max: DropPointMaxAggregateOutputType | null
}

export type GetDropPointGroupByPayload<T extends DropPointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DropPointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DropPointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DropPointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DropPointGroupByOutputType[P]>
      }
    >
  >



export type DropPointWhereInput = {
  AND?: Prisma.DropPointWhereInput | Prisma.DropPointWhereInput[]
  OR?: Prisma.DropPointWhereInput[]
  NOT?: Prisma.DropPointWhereInput | Prisma.DropPointWhereInput[]
  id?: Prisma.StringFilter<"DropPoint"> | string
  name?: Prisma.StringFilter<"DropPoint"> | string
  code?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  province?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  city?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  district?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  address?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  latitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  longitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  contactPerson?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  contactPhone?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  workingHours?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  type?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  description?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  isActive?: Prisma.BoolFilter<"DropPoint"> | boolean
  createdBy?: Prisma.StringFilter<"DropPoint"> | string
  createdAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  pickupLoads?: Prisma.LoadListRelationFilter
  deliveryLoads?: Prisma.LoadListRelationFilter
}

export type DropPointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  province?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  district?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  workingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  pickupLoads?: Prisma.LoadOrderByRelationAggregateInput
  deliveryLoads?: Prisma.LoadOrderByRelationAggregateInput
  _relevance?: Prisma.DropPointOrderByRelevanceInput
}

export type DropPointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.DropPointWhereInput | Prisma.DropPointWhereInput[]
  OR?: Prisma.DropPointWhereInput[]
  NOT?: Prisma.DropPointWhereInput | Prisma.DropPointWhereInput[]
  name?: Prisma.StringFilter<"DropPoint"> | string
  province?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  city?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  district?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  address?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  latitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  longitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  contactPerson?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  contactPhone?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  workingHours?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  type?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  description?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  isActive?: Prisma.BoolFilter<"DropPoint"> | boolean
  createdBy?: Prisma.StringFilter<"DropPoint"> | string
  createdAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  pickupLoads?: Prisma.LoadListRelationFilter
  deliveryLoads?: Prisma.LoadListRelationFilter
}, "id" | "code">

export type DropPointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrderInput | Prisma.SortOrder
  province?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  district?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPerson?: Prisma.SortOrderInput | Prisma.SortOrder
  contactPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  workingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.DropPointCountOrderByAggregateInput
  _avg?: Prisma.DropPointAvgOrderByAggregateInput
  _max?: Prisma.DropPointMaxOrderByAggregateInput
  _min?: Prisma.DropPointMinOrderByAggregateInput
  _sum?: Prisma.DropPointSumOrderByAggregateInput
}

export type DropPointScalarWhereWithAggregatesInput = {
  AND?: Prisma.DropPointScalarWhereWithAggregatesInput | Prisma.DropPointScalarWhereWithAggregatesInput[]
  OR?: Prisma.DropPointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DropPointScalarWhereWithAggregatesInput | Prisma.DropPointScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DropPoint"> | string
  name?: Prisma.StringWithAggregatesFilter<"DropPoint"> | string
  code?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  province?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  city?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  district?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  latitude?: Prisma.FloatNullableWithAggregatesFilter<"DropPoint"> | number | null
  longitude?: Prisma.FloatNullableWithAggregatesFilter<"DropPoint"> | number | null
  contactPerson?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  contactPhone?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  workingHours?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  type?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"DropPoint"> | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"DropPoint"> | boolean
  createdBy?: Prisma.StringWithAggregatesFilter<"DropPoint"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DropPoint"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DropPoint"> | Date | string
}

export type DropPointCreateInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDropPointsInput
  pickupLoads?: Prisma.LoadCreateNestedManyWithoutPickupPointInput
  deliveryLoads?: Prisma.LoadCreateNestedManyWithoutDropPointInput
}

export type DropPointUncheckedCreateInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdBy: string
  createdAt?: Date | string
  updatedAt?: Date | string
  pickupLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutPickupPointInput
  deliveryLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutDropPointInput
}

export type DropPointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDropPointsNestedInput
  pickupLoads?: Prisma.LoadUpdateManyWithoutPickupPointNestedInput
  deliveryLoads?: Prisma.LoadUpdateManyWithoutDropPointNestedInput
}

export type DropPointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pickupLoads?: Prisma.LoadUncheckedUpdateManyWithoutPickupPointNestedInput
  deliveryLoads?: Prisma.LoadUncheckedUpdateManyWithoutDropPointNestedInput
}

export type DropPointCreateManyInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdBy: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DropPointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DropPointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DropPointListRelationFilter = {
  every?: Prisma.DropPointWhereInput
  some?: Prisma.DropPointWhereInput
  none?: Prisma.DropPointWhereInput
}

export type DropPointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DropPointOrderByRelevanceInput = {
  fields: Prisma.DropPointOrderByRelevanceFieldEnum | Prisma.DropPointOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type DropPointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  province?: Prisma.SortOrder
  city?: Prisma.SortOrder
  district?: Prisma.SortOrder
  address?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  workingHours?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DropPointAvgOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type DropPointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  province?: Prisma.SortOrder
  city?: Prisma.SortOrder
  district?: Prisma.SortOrder
  address?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  workingHours?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DropPointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  code?: Prisma.SortOrder
  province?: Prisma.SortOrder
  city?: Prisma.SortOrder
  district?: Prisma.SortOrder
  address?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  contactPerson?: Prisma.SortOrder
  contactPhone?: Prisma.SortOrder
  workingHours?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type DropPointSumOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type DropPointScalarRelationFilter = {
  is?: Prisma.DropPointWhereInput
  isNot?: Prisma.DropPointWhereInput
}

export type DropPointCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput> | Prisma.DropPointCreateWithoutUserInput[] | Prisma.DropPointUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutUserInput | Prisma.DropPointCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DropPointCreateManyUserInputEnvelope
  connect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
}

export type DropPointUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput> | Prisma.DropPointCreateWithoutUserInput[] | Prisma.DropPointUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutUserInput | Prisma.DropPointCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.DropPointCreateManyUserInputEnvelope
  connect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
}

export type DropPointUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput> | Prisma.DropPointCreateWithoutUserInput[] | Prisma.DropPointUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutUserInput | Prisma.DropPointCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DropPointUpsertWithWhereUniqueWithoutUserInput | Prisma.DropPointUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DropPointCreateManyUserInputEnvelope
  set?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  disconnect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  delete?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  connect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  update?: Prisma.DropPointUpdateWithWhereUniqueWithoutUserInput | Prisma.DropPointUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DropPointUpdateManyWithWhereWithoutUserInput | Prisma.DropPointUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DropPointScalarWhereInput | Prisma.DropPointScalarWhereInput[]
}

export type DropPointUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput> | Prisma.DropPointCreateWithoutUserInput[] | Prisma.DropPointUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutUserInput | Prisma.DropPointCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.DropPointUpsertWithWhereUniqueWithoutUserInput | Prisma.DropPointUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.DropPointCreateManyUserInputEnvelope
  set?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  disconnect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  delete?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  connect?: Prisma.DropPointWhereUniqueInput | Prisma.DropPointWhereUniqueInput[]
  update?: Prisma.DropPointUpdateWithWhereUniqueWithoutUserInput | Prisma.DropPointUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.DropPointUpdateManyWithWhereWithoutUserInput | Prisma.DropPointUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.DropPointScalarWhereInput | Prisma.DropPointScalarWhereInput[]
}

export type DropPointCreateNestedOneWithoutPickupLoadsInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutPickupLoadsInput, Prisma.DropPointUncheckedCreateWithoutPickupLoadsInput>
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutPickupLoadsInput
  connect?: Prisma.DropPointWhereUniqueInput
}

export type DropPointCreateNestedOneWithoutDeliveryLoadsInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedCreateWithoutDeliveryLoadsInput>
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutDeliveryLoadsInput
  connect?: Prisma.DropPointWhereUniqueInput
}

export type DropPointUpdateOneRequiredWithoutPickupLoadsNestedInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutPickupLoadsInput, Prisma.DropPointUncheckedCreateWithoutPickupLoadsInput>
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutPickupLoadsInput
  upsert?: Prisma.DropPointUpsertWithoutPickupLoadsInput
  connect?: Prisma.DropPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DropPointUpdateToOneWithWhereWithoutPickupLoadsInput, Prisma.DropPointUpdateWithoutPickupLoadsInput>, Prisma.DropPointUncheckedUpdateWithoutPickupLoadsInput>
}

export type DropPointUpdateOneRequiredWithoutDeliveryLoadsNestedInput = {
  create?: Prisma.XOR<Prisma.DropPointCreateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedCreateWithoutDeliveryLoadsInput>
  connectOrCreate?: Prisma.DropPointCreateOrConnectWithoutDeliveryLoadsInput
  upsert?: Prisma.DropPointUpsertWithoutDeliveryLoadsInput
  connect?: Prisma.DropPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DropPointUpdateToOneWithWhereWithoutDeliveryLoadsInput, Prisma.DropPointUpdateWithoutDeliveryLoadsInput>, Prisma.DropPointUncheckedUpdateWithoutDeliveryLoadsInput>
}

export type DropPointCreateWithoutUserInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  pickupLoads?: Prisma.LoadCreateNestedManyWithoutPickupPointInput
  deliveryLoads?: Prisma.LoadCreateNestedManyWithoutDropPointInput
}

export type DropPointUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  pickupLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutPickupPointInput
  deliveryLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutDropPointInput
}

export type DropPointCreateOrConnectWithoutUserInput = {
  where: Prisma.DropPointWhereUniqueInput
  create: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput>
}

export type DropPointCreateManyUserInputEnvelope = {
  data: Prisma.DropPointCreateManyUserInput | Prisma.DropPointCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type DropPointUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.DropPointWhereUniqueInput
  update: Prisma.XOR<Prisma.DropPointUpdateWithoutUserInput, Prisma.DropPointUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.DropPointCreateWithoutUserInput, Prisma.DropPointUncheckedCreateWithoutUserInput>
}

export type DropPointUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.DropPointWhereUniqueInput
  data: Prisma.XOR<Prisma.DropPointUpdateWithoutUserInput, Prisma.DropPointUncheckedUpdateWithoutUserInput>
}

export type DropPointUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.DropPointScalarWhereInput
  data: Prisma.XOR<Prisma.DropPointUpdateManyMutationInput, Prisma.DropPointUncheckedUpdateManyWithoutUserInput>
}

export type DropPointScalarWhereInput = {
  AND?: Prisma.DropPointScalarWhereInput | Prisma.DropPointScalarWhereInput[]
  OR?: Prisma.DropPointScalarWhereInput[]
  NOT?: Prisma.DropPointScalarWhereInput | Prisma.DropPointScalarWhereInput[]
  id?: Prisma.StringFilter<"DropPoint"> | string
  name?: Prisma.StringFilter<"DropPoint"> | string
  code?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  province?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  city?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  district?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  address?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  latitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  longitude?: Prisma.FloatNullableFilter<"DropPoint"> | number | null
  contactPerson?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  contactPhone?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  workingHours?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  type?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  description?: Prisma.StringNullableFilter<"DropPoint"> | string | null
  isActive?: Prisma.BoolFilter<"DropPoint"> | boolean
  createdBy?: Prisma.StringFilter<"DropPoint"> | string
  createdAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DropPoint"> | Date | string
}

export type DropPointCreateWithoutPickupLoadsInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDropPointsInput
  deliveryLoads?: Prisma.LoadCreateNestedManyWithoutDropPointInput
}

export type DropPointUncheckedCreateWithoutPickupLoadsInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdBy: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deliveryLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutDropPointInput
}

export type DropPointCreateOrConnectWithoutPickupLoadsInput = {
  where: Prisma.DropPointWhereUniqueInput
  create: Prisma.XOR<Prisma.DropPointCreateWithoutPickupLoadsInput, Prisma.DropPointUncheckedCreateWithoutPickupLoadsInput>
}

export type DropPointCreateWithoutDeliveryLoadsInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutDropPointsInput
  pickupLoads?: Prisma.LoadCreateNestedManyWithoutPickupPointInput
}

export type DropPointUncheckedCreateWithoutDeliveryLoadsInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdBy: string
  createdAt?: Date | string
  updatedAt?: Date | string
  pickupLoads?: Prisma.LoadUncheckedCreateNestedManyWithoutPickupPointInput
}

export type DropPointCreateOrConnectWithoutDeliveryLoadsInput = {
  where: Prisma.DropPointWhereUniqueInput
  create: Prisma.XOR<Prisma.DropPointCreateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedCreateWithoutDeliveryLoadsInput>
}

export type DropPointUpsertWithoutPickupLoadsInput = {
  update: Prisma.XOR<Prisma.DropPointUpdateWithoutPickupLoadsInput, Prisma.DropPointUncheckedUpdateWithoutPickupLoadsInput>
  create: Prisma.XOR<Prisma.DropPointCreateWithoutPickupLoadsInput, Prisma.DropPointUncheckedCreateWithoutPickupLoadsInput>
  where?: Prisma.DropPointWhereInput
}

export type DropPointUpdateToOneWithWhereWithoutPickupLoadsInput = {
  where?: Prisma.DropPointWhereInput
  data: Prisma.XOR<Prisma.DropPointUpdateWithoutPickupLoadsInput, Prisma.DropPointUncheckedUpdateWithoutPickupLoadsInput>
}

export type DropPointUpdateWithoutPickupLoadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDropPointsNestedInput
  deliveryLoads?: Prisma.LoadUpdateManyWithoutDropPointNestedInput
}

export type DropPointUncheckedUpdateWithoutPickupLoadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deliveryLoads?: Prisma.LoadUncheckedUpdateManyWithoutDropPointNestedInput
}

export type DropPointUpsertWithoutDeliveryLoadsInput = {
  update: Prisma.XOR<Prisma.DropPointUpdateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedUpdateWithoutDeliveryLoadsInput>
  create: Prisma.XOR<Prisma.DropPointCreateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedCreateWithoutDeliveryLoadsInput>
  where?: Prisma.DropPointWhereInput
}

export type DropPointUpdateToOneWithWhereWithoutDeliveryLoadsInput = {
  where?: Prisma.DropPointWhereInput
  data: Prisma.XOR<Prisma.DropPointUpdateWithoutDeliveryLoadsInput, Prisma.DropPointUncheckedUpdateWithoutDeliveryLoadsInput>
}

export type DropPointUpdateWithoutDeliveryLoadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutDropPointsNestedInput
  pickupLoads?: Prisma.LoadUpdateManyWithoutPickupPointNestedInput
}

export type DropPointUncheckedUpdateWithoutDeliveryLoadsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pickupLoads?: Prisma.LoadUncheckedUpdateManyWithoutPickupPointNestedInput
}

export type DropPointCreateManyUserInput = {
  id?: string
  name: string
  code?: string | null
  province?: string | null
  city?: string | null
  district?: string | null
  address?: string | null
  latitude?: number | null
  longitude?: number | null
  contactPerson?: string | null
  contactPhone?: string | null
  workingHours?: string | null
  type?: string | null
  description?: string | null
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DropPointUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pickupLoads?: Prisma.LoadUpdateManyWithoutPickupPointNestedInput
  deliveryLoads?: Prisma.LoadUpdateManyWithoutDropPointNestedInput
}

export type DropPointUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pickupLoads?: Prisma.LoadUncheckedUpdateManyWithoutPickupPointNestedInput
  deliveryLoads?: Prisma.LoadUncheckedUpdateManyWithoutDropPointNestedInput
}

export type DropPointUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  province?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  district?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  contactPerson?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contactPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DropPointCountOutputType
 */

export type DropPointCountOutputType = {
  pickupLoads: number
  deliveryLoads: number
}

export type DropPointCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pickupLoads?: boolean | DropPointCountOutputTypeCountPickupLoadsArgs
  deliveryLoads?: boolean | DropPointCountOutputTypeCountDeliveryLoadsArgs
}

/**
 * DropPointCountOutputType without action
 */
export type DropPointCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPointCountOutputType
   */
  select?: Prisma.DropPointCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DropPointCountOutputType without action
 */
export type DropPointCountOutputTypeCountPickupLoadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoadWhereInput
}

/**
 * DropPointCountOutputType without action
 */
export type DropPointCountOutputTypeCountDeliveryLoadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoadWhereInput
}


export type DropPointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  code?: boolean
  province?: boolean
  city?: boolean
  district?: boolean
  address?: boolean
  latitude?: boolean
  longitude?: boolean
  contactPerson?: boolean
  contactPhone?: boolean
  workingHours?: boolean
  type?: boolean
  description?: boolean
  isActive?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  pickupLoads?: boolean | Prisma.DropPoint$pickupLoadsArgs<ExtArgs>
  deliveryLoads?: boolean | Prisma.DropPoint$deliveryLoadsArgs<ExtArgs>
  _count?: boolean | Prisma.DropPointCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dropPoint"]>



export type DropPointSelectScalar = {
  id?: boolean
  name?: boolean
  code?: boolean
  province?: boolean
  city?: boolean
  district?: boolean
  address?: boolean
  latitude?: boolean
  longitude?: boolean
  contactPerson?: boolean
  contactPhone?: boolean
  workingHours?: boolean
  type?: boolean
  description?: boolean
  isActive?: boolean
  createdBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type DropPointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "code" | "province" | "city" | "district" | "address" | "latitude" | "longitude" | "contactPerson" | "contactPhone" | "workingHours" | "type" | "description" | "isActive" | "createdBy" | "createdAt" | "updatedAt", ExtArgs["result"]["dropPoint"]>
export type DropPointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  pickupLoads?: boolean | Prisma.DropPoint$pickupLoadsArgs<ExtArgs>
  deliveryLoads?: boolean | Prisma.DropPoint$deliveryLoadsArgs<ExtArgs>
  _count?: boolean | Prisma.DropPointCountOutputTypeDefaultArgs<ExtArgs>
}

export type $DropPointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DropPoint"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    pickupLoads: Prisma.$LoadPayload<ExtArgs>[]
    deliveryLoads: Prisma.$LoadPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    code: string | null
    province: string | null
    city: string | null
    district: string | null
    address: string | null
    latitude: number | null
    longitude: number | null
    contactPerson: string | null
    contactPhone: string | null
    workingHours: string | null
    type: string | null
    description: string | null
    isActive: boolean
    createdBy: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["dropPoint"]>
  composites: {}
}

export type DropPointGetPayload<S extends boolean | null | undefined | DropPointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DropPointPayload, S>

export type DropPointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DropPointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DropPointCountAggregateInputType | true
  }

export interface DropPointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DropPoint'], meta: { name: 'DropPoint' } }
  /**
   * Find zero or one DropPoint that matches the filter.
   * @param {DropPointFindUniqueArgs} args - Arguments to find a DropPoint
   * @example
   * // Get one DropPoint
   * const dropPoint = await prisma.dropPoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DropPointFindUniqueArgs>(args: Prisma.SelectSubset<T, DropPointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DropPoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DropPointFindUniqueOrThrowArgs} args - Arguments to find a DropPoint
   * @example
   * // Get one DropPoint
   * const dropPoint = await prisma.dropPoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DropPointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DropPointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DropPoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointFindFirstArgs} args - Arguments to find a DropPoint
   * @example
   * // Get one DropPoint
   * const dropPoint = await prisma.dropPoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DropPointFindFirstArgs>(args?: Prisma.SelectSubset<T, DropPointFindFirstArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DropPoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointFindFirstOrThrowArgs} args - Arguments to find a DropPoint
   * @example
   * // Get one DropPoint
   * const dropPoint = await prisma.dropPoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DropPointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DropPointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DropPoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DropPoints
   * const dropPoints = await prisma.dropPoint.findMany()
   * 
   * // Get first 10 DropPoints
   * const dropPoints = await prisma.dropPoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dropPointWithIdOnly = await prisma.dropPoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DropPointFindManyArgs>(args?: Prisma.SelectSubset<T, DropPointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DropPoint.
   * @param {DropPointCreateArgs} args - Arguments to create a DropPoint.
   * @example
   * // Create one DropPoint
   * const DropPoint = await prisma.dropPoint.create({
   *   data: {
   *     // ... data to create a DropPoint
   *   }
   * })
   * 
   */
  create<T extends DropPointCreateArgs>(args: Prisma.SelectSubset<T, DropPointCreateArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DropPoints.
   * @param {DropPointCreateManyArgs} args - Arguments to create many DropPoints.
   * @example
   * // Create many DropPoints
   * const dropPoint = await prisma.dropPoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DropPointCreateManyArgs>(args?: Prisma.SelectSubset<T, DropPointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DropPoint.
   * @param {DropPointDeleteArgs} args - Arguments to delete one DropPoint.
   * @example
   * // Delete one DropPoint
   * const DropPoint = await prisma.dropPoint.delete({
   *   where: {
   *     // ... filter to delete one DropPoint
   *   }
   * })
   * 
   */
  delete<T extends DropPointDeleteArgs>(args: Prisma.SelectSubset<T, DropPointDeleteArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DropPoint.
   * @param {DropPointUpdateArgs} args - Arguments to update one DropPoint.
   * @example
   * // Update one DropPoint
   * const dropPoint = await prisma.dropPoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DropPointUpdateArgs>(args: Prisma.SelectSubset<T, DropPointUpdateArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DropPoints.
   * @param {DropPointDeleteManyArgs} args - Arguments to filter DropPoints to delete.
   * @example
   * // Delete a few DropPoints
   * const { count } = await prisma.dropPoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DropPointDeleteManyArgs>(args?: Prisma.SelectSubset<T, DropPointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DropPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DropPoints
   * const dropPoint = await prisma.dropPoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DropPointUpdateManyArgs>(args: Prisma.SelectSubset<T, DropPointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DropPoint.
   * @param {DropPointUpsertArgs} args - Arguments to update or create a DropPoint.
   * @example
   * // Update or create a DropPoint
   * const dropPoint = await prisma.dropPoint.upsert({
   *   create: {
   *     // ... data to create a DropPoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DropPoint we want to update
   *   }
   * })
   */
  upsert<T extends DropPointUpsertArgs>(args: Prisma.SelectSubset<T, DropPointUpsertArgs<ExtArgs>>): Prisma.Prisma__DropPointClient<runtime.Types.Result.GetResult<Prisma.$DropPointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DropPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointCountArgs} args - Arguments to filter DropPoints to count.
   * @example
   * // Count the number of DropPoints
   * const count = await prisma.dropPoint.count({
   *   where: {
   *     // ... the filter for the DropPoints we want to count
   *   }
   * })
  **/
  count<T extends DropPointCountArgs>(
    args?: Prisma.Subset<T, DropPointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DropPointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DropPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DropPointAggregateArgs>(args: Prisma.Subset<T, DropPointAggregateArgs>): Prisma.PrismaPromise<GetDropPointAggregateType<T>>

  /**
   * Group by DropPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DropPointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DropPointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DropPointGroupByArgs['orderBy'] }
      : { orderBy?: DropPointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DropPointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDropPointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DropPoint model
 */
readonly fields: DropPointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DropPoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DropPointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  pickupLoads<T extends Prisma.DropPoint$pickupLoadsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DropPoint$pickupLoadsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  deliveryLoads<T extends Prisma.DropPoint$deliveryLoadsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DropPoint$deliveryLoadsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DropPoint model
 */
export interface DropPointFieldRefs {
  readonly id: Prisma.FieldRef<"DropPoint", 'String'>
  readonly name: Prisma.FieldRef<"DropPoint", 'String'>
  readonly code: Prisma.FieldRef<"DropPoint", 'String'>
  readonly province: Prisma.FieldRef<"DropPoint", 'String'>
  readonly city: Prisma.FieldRef<"DropPoint", 'String'>
  readonly district: Prisma.FieldRef<"DropPoint", 'String'>
  readonly address: Prisma.FieldRef<"DropPoint", 'String'>
  readonly latitude: Prisma.FieldRef<"DropPoint", 'Float'>
  readonly longitude: Prisma.FieldRef<"DropPoint", 'Float'>
  readonly contactPerson: Prisma.FieldRef<"DropPoint", 'String'>
  readonly contactPhone: Prisma.FieldRef<"DropPoint", 'String'>
  readonly workingHours: Prisma.FieldRef<"DropPoint", 'String'>
  readonly type: Prisma.FieldRef<"DropPoint", 'String'>
  readonly description: Prisma.FieldRef<"DropPoint", 'String'>
  readonly isActive: Prisma.FieldRef<"DropPoint", 'Boolean'>
  readonly createdBy: Prisma.FieldRef<"DropPoint", 'String'>
  readonly createdAt: Prisma.FieldRef<"DropPoint", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DropPoint", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DropPoint findUnique
 */
export type DropPointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter, which DropPoint to fetch.
   */
  where: Prisma.DropPointWhereUniqueInput
}

/**
 * DropPoint findUniqueOrThrow
 */
export type DropPointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter, which DropPoint to fetch.
   */
  where: Prisma.DropPointWhereUniqueInput
}

/**
 * DropPoint findFirst
 */
export type DropPointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter, which DropPoint to fetch.
   */
  where?: Prisma.DropPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DropPoints to fetch.
   */
  orderBy?: Prisma.DropPointOrderByWithRelationInput | Prisma.DropPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DropPoints.
   */
  cursor?: Prisma.DropPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DropPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DropPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DropPoints.
   */
  distinct?: Prisma.DropPointScalarFieldEnum | Prisma.DropPointScalarFieldEnum[]
}

/**
 * DropPoint findFirstOrThrow
 */
export type DropPointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter, which DropPoint to fetch.
   */
  where?: Prisma.DropPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DropPoints to fetch.
   */
  orderBy?: Prisma.DropPointOrderByWithRelationInput | Prisma.DropPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DropPoints.
   */
  cursor?: Prisma.DropPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DropPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DropPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DropPoints.
   */
  distinct?: Prisma.DropPointScalarFieldEnum | Prisma.DropPointScalarFieldEnum[]
}

/**
 * DropPoint findMany
 */
export type DropPointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter, which DropPoints to fetch.
   */
  where?: Prisma.DropPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DropPoints to fetch.
   */
  orderBy?: Prisma.DropPointOrderByWithRelationInput | Prisma.DropPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DropPoints.
   */
  cursor?: Prisma.DropPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DropPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DropPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DropPoints.
   */
  distinct?: Prisma.DropPointScalarFieldEnum | Prisma.DropPointScalarFieldEnum[]
}

/**
 * DropPoint create
 */
export type DropPointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * The data needed to create a DropPoint.
   */
  data: Prisma.XOR<Prisma.DropPointCreateInput, Prisma.DropPointUncheckedCreateInput>
}

/**
 * DropPoint createMany
 */
export type DropPointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DropPoints.
   */
  data: Prisma.DropPointCreateManyInput | Prisma.DropPointCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DropPoint update
 */
export type DropPointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * The data needed to update a DropPoint.
   */
  data: Prisma.XOR<Prisma.DropPointUpdateInput, Prisma.DropPointUncheckedUpdateInput>
  /**
   * Choose, which DropPoint to update.
   */
  where: Prisma.DropPointWhereUniqueInput
}

/**
 * DropPoint updateMany
 */
export type DropPointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DropPoints.
   */
  data: Prisma.XOR<Prisma.DropPointUpdateManyMutationInput, Prisma.DropPointUncheckedUpdateManyInput>
  /**
   * Filter which DropPoints to update
   */
  where?: Prisma.DropPointWhereInput
  /**
   * Limit how many DropPoints to update.
   */
  limit?: number
}

/**
 * DropPoint upsert
 */
export type DropPointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * The filter to search for the DropPoint to update in case it exists.
   */
  where: Prisma.DropPointWhereUniqueInput
  /**
   * In case the DropPoint found by the `where` argument doesn't exist, create a new DropPoint with this data.
   */
  create: Prisma.XOR<Prisma.DropPointCreateInput, Prisma.DropPointUncheckedCreateInput>
  /**
   * In case the DropPoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DropPointUpdateInput, Prisma.DropPointUncheckedUpdateInput>
}

/**
 * DropPoint delete
 */
export type DropPointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
  /**
   * Filter which DropPoint to delete.
   */
  where: Prisma.DropPointWhereUniqueInput
}

/**
 * DropPoint deleteMany
 */
export type DropPointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DropPoints to delete
   */
  where?: Prisma.DropPointWhereInput
  /**
   * Limit how many DropPoints to delete.
   */
  limit?: number
}

/**
 * DropPoint.pickupLoads
 */
export type DropPoint$pickupLoadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Load
   */
  select?: Prisma.LoadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Load
   */
  omit?: Prisma.LoadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadInclude<ExtArgs> | null
  where?: Prisma.LoadWhereInput
  orderBy?: Prisma.LoadOrderByWithRelationInput | Prisma.LoadOrderByWithRelationInput[]
  cursor?: Prisma.LoadWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LoadScalarFieldEnum | Prisma.LoadScalarFieldEnum[]
}

/**
 * DropPoint.deliveryLoads
 */
export type DropPoint$deliveryLoadsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Load
   */
  select?: Prisma.LoadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Load
   */
  omit?: Prisma.LoadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadInclude<ExtArgs> | null
  where?: Prisma.LoadWhereInput
  orderBy?: Prisma.LoadOrderByWithRelationInput | Prisma.LoadOrderByWithRelationInput[]
  cursor?: Prisma.LoadWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LoadScalarFieldEnum | Prisma.LoadScalarFieldEnum[]
}

/**
 * DropPoint without action
 */
export type DropPointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DropPoint
   */
  select?: Prisma.DropPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DropPoint
   */
  omit?: Prisma.DropPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DropPointInclude<ExtArgs> | null
}
