
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LoadHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LoadHistory
 * 
 */
export type LoadHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$LoadHistoryPayload>

export type AggregateLoadHistory = {
  _count: LoadHistoryCountAggregateOutputType | null
  _min: LoadHistoryMinAggregateOutputType | null
  _max: LoadHistoryMaxAggregateOutputType | null
}

export type LoadHistoryMinAggregateOutputType = {
  id: string | null
  loadId: string | null
  action: string | null
  description: string | null
  changedBy: string | null
  createdAt: Date | null
}

export type LoadHistoryMaxAggregateOutputType = {
  id: string | null
  loadId: string | null
  action: string | null
  description: string | null
  changedBy: string | null
  createdAt: Date | null
}

export type LoadHistoryCountAggregateOutputType = {
  id: number
  loadId: number
  action: number
  description: number
  changedBy: number
  createdAt: number
  _all: number
}


export type LoadHistoryMinAggregateInputType = {
  id?: true
  loadId?: true
  action?: true
  description?: true
  changedBy?: true
  createdAt?: true
}

export type LoadHistoryMaxAggregateInputType = {
  id?: true
  loadId?: true
  action?: true
  description?: true
  changedBy?: true
  createdAt?: true
}

export type LoadHistoryCountAggregateInputType = {
  id?: true
  loadId?: true
  action?: true
  description?: true
  changedBy?: true
  createdAt?: true
  _all?: true
}

export type LoadHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoadHistory to aggregate.
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoadHistories to fetch.
   */
  orderBy?: Prisma.LoadHistoryOrderByWithRelationInput | Prisma.LoadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LoadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LoadHistories
  **/
  _count?: true | LoadHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LoadHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LoadHistoryMaxAggregateInputType
}

export type GetLoadHistoryAggregateType<T extends LoadHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateLoadHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLoadHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateLoadHistory[P]>
}




export type LoadHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LoadHistoryWhereInput
  orderBy?: Prisma.LoadHistoryOrderByWithAggregationInput | Prisma.LoadHistoryOrderByWithAggregationInput[]
  by: Prisma.LoadHistoryScalarFieldEnum[] | Prisma.LoadHistoryScalarFieldEnum
  having?: Prisma.LoadHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LoadHistoryCountAggregateInputType | true
  _min?: LoadHistoryMinAggregateInputType
  _max?: LoadHistoryMaxAggregateInputType
}

export type LoadHistoryGroupByOutputType = {
  id: string
  loadId: string
  action: string
  description: string | null
  changedBy: string
  createdAt: Date
  _count: LoadHistoryCountAggregateOutputType | null
  _min: LoadHistoryMinAggregateOutputType | null
  _max: LoadHistoryMaxAggregateOutputType | null
}

export type GetLoadHistoryGroupByPayload<T extends LoadHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LoadHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LoadHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LoadHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LoadHistoryGroupByOutputType[P]>
      }
    >
  >



export type LoadHistoryWhereInput = {
  AND?: Prisma.LoadHistoryWhereInput | Prisma.LoadHistoryWhereInput[]
  OR?: Prisma.LoadHistoryWhereInput[]
  NOT?: Prisma.LoadHistoryWhereInput | Prisma.LoadHistoryWhereInput[]
  id?: Prisma.StringFilter<"LoadHistory"> | string
  loadId?: Prisma.StringFilter<"LoadHistory"> | string
  action?: Prisma.StringFilter<"LoadHistory"> | string
  description?: Prisma.StringNullableFilter<"LoadHistory"> | string | null
  changedBy?: Prisma.StringFilter<"LoadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"LoadHistory"> | Date | string
  load?: Prisma.XOR<Prisma.LoadScalarRelationFilter, Prisma.LoadWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LoadHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  loadId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  load?: Prisma.LoadOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  _relevance?: Prisma.LoadHistoryOrderByRelevanceInput
}

export type LoadHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LoadHistoryWhereInput | Prisma.LoadHistoryWhereInput[]
  OR?: Prisma.LoadHistoryWhereInput[]
  NOT?: Prisma.LoadHistoryWhereInput | Prisma.LoadHistoryWhereInput[]
  loadId?: Prisma.StringFilter<"LoadHistory"> | string
  action?: Prisma.StringFilter<"LoadHistory"> | string
  description?: Prisma.StringNullableFilter<"LoadHistory"> | string | null
  changedBy?: Prisma.StringFilter<"LoadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"LoadHistory"> | Date | string
  load?: Prisma.XOR<Prisma.LoadScalarRelationFilter, Prisma.LoadWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type LoadHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  loadId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.LoadHistoryCountOrderByAggregateInput
  _max?: Prisma.LoadHistoryMaxOrderByAggregateInput
  _min?: Prisma.LoadHistoryMinOrderByAggregateInput
}

export type LoadHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.LoadHistoryScalarWhereWithAggregatesInput | Prisma.LoadHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.LoadHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LoadHistoryScalarWhereWithAggregatesInput | Prisma.LoadHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LoadHistory"> | string
  loadId?: Prisma.StringWithAggregatesFilter<"LoadHistory"> | string
  action?: Prisma.StringWithAggregatesFilter<"LoadHistory"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"LoadHistory"> | string | null
  changedBy?: Prisma.StringWithAggregatesFilter<"LoadHistory"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LoadHistory"> | Date | string
}

export type LoadHistoryCreateInput = {
  id?: string
  action: string
  description?: string | null
  createdAt?: Date | string
  load: Prisma.LoadCreateNestedOneWithoutHistoryInput
  user: Prisma.UserCreateNestedOneWithoutLoadHistoryInput
}

export type LoadHistoryUncheckedCreateInput = {
  id?: string
  loadId: string
  action: string
  description?: string | null
  changedBy: string
  createdAt?: Date | string
}

export type LoadHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  load?: Prisma.LoadUpdateOneRequiredWithoutHistoryNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutLoadHistoryNestedInput
}

export type LoadHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loadId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryCreateManyInput = {
  id?: string
  loadId: string
  action: string
  description?: string | null
  changedBy: string
  createdAt?: Date | string
}

export type LoadHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loadId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryListRelationFilter = {
  every?: Prisma.LoadHistoryWhereInput
  some?: Prisma.LoadHistoryWhereInput
  none?: Prisma.LoadHistoryWhereInput
}

export type LoadHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LoadHistoryOrderByRelevanceInput = {
  fields: Prisma.LoadHistoryOrderByRelevanceFieldEnum | Prisma.LoadHistoryOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type LoadHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loadId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  description?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LoadHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loadId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  description?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LoadHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  loadId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  description?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type LoadHistoryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput> | Prisma.LoadHistoryCreateWithoutUserInput[] | Prisma.LoadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutUserInput | Prisma.LoadHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LoadHistoryCreateManyUserInputEnvelope
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
}

export type LoadHistoryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput> | Prisma.LoadHistoryCreateWithoutUserInput[] | Prisma.LoadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutUserInput | Prisma.LoadHistoryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LoadHistoryCreateManyUserInputEnvelope
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
}

export type LoadHistoryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput> | Prisma.LoadHistoryCreateWithoutUserInput[] | Prisma.LoadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutUserInput | Prisma.LoadHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LoadHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.LoadHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LoadHistoryCreateManyUserInputEnvelope
  set?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  delete?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  update?: Prisma.LoadHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.LoadHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LoadHistoryUpdateManyWithWhereWithoutUserInput | Prisma.LoadHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
}

export type LoadHistoryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput> | Prisma.LoadHistoryCreateWithoutUserInput[] | Prisma.LoadHistoryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutUserInput | Prisma.LoadHistoryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LoadHistoryUpsertWithWhereUniqueWithoutUserInput | Prisma.LoadHistoryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LoadHistoryCreateManyUserInputEnvelope
  set?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  delete?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  update?: Prisma.LoadHistoryUpdateWithWhereUniqueWithoutUserInput | Prisma.LoadHistoryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LoadHistoryUpdateManyWithWhereWithoutUserInput | Prisma.LoadHistoryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
}

export type LoadHistoryCreateNestedManyWithoutLoadInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput> | Prisma.LoadHistoryCreateWithoutLoadInput[] | Prisma.LoadHistoryUncheckedCreateWithoutLoadInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutLoadInput | Prisma.LoadHistoryCreateOrConnectWithoutLoadInput[]
  createMany?: Prisma.LoadHistoryCreateManyLoadInputEnvelope
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
}

export type LoadHistoryUncheckedCreateNestedManyWithoutLoadInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput> | Prisma.LoadHistoryCreateWithoutLoadInput[] | Prisma.LoadHistoryUncheckedCreateWithoutLoadInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutLoadInput | Prisma.LoadHistoryCreateOrConnectWithoutLoadInput[]
  createMany?: Prisma.LoadHistoryCreateManyLoadInputEnvelope
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
}

export type LoadHistoryUpdateManyWithoutLoadNestedInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput> | Prisma.LoadHistoryCreateWithoutLoadInput[] | Prisma.LoadHistoryUncheckedCreateWithoutLoadInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutLoadInput | Prisma.LoadHistoryCreateOrConnectWithoutLoadInput[]
  upsert?: Prisma.LoadHistoryUpsertWithWhereUniqueWithoutLoadInput | Prisma.LoadHistoryUpsertWithWhereUniqueWithoutLoadInput[]
  createMany?: Prisma.LoadHistoryCreateManyLoadInputEnvelope
  set?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  delete?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  update?: Prisma.LoadHistoryUpdateWithWhereUniqueWithoutLoadInput | Prisma.LoadHistoryUpdateWithWhereUniqueWithoutLoadInput[]
  updateMany?: Prisma.LoadHistoryUpdateManyWithWhereWithoutLoadInput | Prisma.LoadHistoryUpdateManyWithWhereWithoutLoadInput[]
  deleteMany?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
}

export type LoadHistoryUncheckedUpdateManyWithoutLoadNestedInput = {
  create?: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput> | Prisma.LoadHistoryCreateWithoutLoadInput[] | Prisma.LoadHistoryUncheckedCreateWithoutLoadInput[]
  connectOrCreate?: Prisma.LoadHistoryCreateOrConnectWithoutLoadInput | Prisma.LoadHistoryCreateOrConnectWithoutLoadInput[]
  upsert?: Prisma.LoadHistoryUpsertWithWhereUniqueWithoutLoadInput | Prisma.LoadHistoryUpsertWithWhereUniqueWithoutLoadInput[]
  createMany?: Prisma.LoadHistoryCreateManyLoadInputEnvelope
  set?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  disconnect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  delete?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  connect?: Prisma.LoadHistoryWhereUniqueInput | Prisma.LoadHistoryWhereUniqueInput[]
  update?: Prisma.LoadHistoryUpdateWithWhereUniqueWithoutLoadInput | Prisma.LoadHistoryUpdateWithWhereUniqueWithoutLoadInput[]
  updateMany?: Prisma.LoadHistoryUpdateManyWithWhereWithoutLoadInput | Prisma.LoadHistoryUpdateManyWithWhereWithoutLoadInput[]
  deleteMany?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
}

export type LoadHistoryCreateWithoutUserInput = {
  id?: string
  action: string
  description?: string | null
  createdAt?: Date | string
  load: Prisma.LoadCreateNestedOneWithoutHistoryInput
}

export type LoadHistoryUncheckedCreateWithoutUserInput = {
  id?: string
  loadId: string
  action: string
  description?: string | null
  createdAt?: Date | string
}

export type LoadHistoryCreateOrConnectWithoutUserInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput>
}

export type LoadHistoryCreateManyUserInputEnvelope = {
  data: Prisma.LoadHistoryCreateManyUserInput | Prisma.LoadHistoryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type LoadHistoryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.LoadHistoryUpdateWithoutUserInput, Prisma.LoadHistoryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LoadHistoryCreateWithoutUserInput, Prisma.LoadHistoryUncheckedCreateWithoutUserInput>
}

export type LoadHistoryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.LoadHistoryUpdateWithoutUserInput, Prisma.LoadHistoryUncheckedUpdateWithoutUserInput>
}

export type LoadHistoryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LoadHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.LoadHistoryUpdateManyMutationInput, Prisma.LoadHistoryUncheckedUpdateManyWithoutUserInput>
}

export type LoadHistoryScalarWhereInput = {
  AND?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
  OR?: Prisma.LoadHistoryScalarWhereInput[]
  NOT?: Prisma.LoadHistoryScalarWhereInput | Prisma.LoadHistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"LoadHistory"> | string
  loadId?: Prisma.StringFilter<"LoadHistory"> | string
  action?: Prisma.StringFilter<"LoadHistory"> | string
  description?: Prisma.StringNullableFilter<"LoadHistory"> | string | null
  changedBy?: Prisma.StringFilter<"LoadHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"LoadHistory"> | Date | string
}

export type LoadHistoryCreateWithoutLoadInput = {
  id?: string
  action: string
  description?: string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLoadHistoryInput
}

export type LoadHistoryUncheckedCreateWithoutLoadInput = {
  id?: string
  action: string
  description?: string | null
  changedBy: string
  createdAt?: Date | string
}

export type LoadHistoryCreateOrConnectWithoutLoadInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput>
}

export type LoadHistoryCreateManyLoadInputEnvelope = {
  data: Prisma.LoadHistoryCreateManyLoadInput | Prisma.LoadHistoryCreateManyLoadInput[]
  skipDuplicates?: boolean
}

export type LoadHistoryUpsertWithWhereUniqueWithoutLoadInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.LoadHistoryUpdateWithoutLoadInput, Prisma.LoadHistoryUncheckedUpdateWithoutLoadInput>
  create: Prisma.XOR<Prisma.LoadHistoryCreateWithoutLoadInput, Prisma.LoadHistoryUncheckedCreateWithoutLoadInput>
}

export type LoadHistoryUpdateWithWhereUniqueWithoutLoadInput = {
  where: Prisma.LoadHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.LoadHistoryUpdateWithoutLoadInput, Prisma.LoadHistoryUncheckedUpdateWithoutLoadInput>
}

export type LoadHistoryUpdateManyWithWhereWithoutLoadInput = {
  where: Prisma.LoadHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.LoadHistoryUpdateManyMutationInput, Prisma.LoadHistoryUncheckedUpdateManyWithoutLoadInput>
}

export type LoadHistoryCreateManyUserInput = {
  id?: string
  loadId: string
  action: string
  description?: string | null
  createdAt?: Date | string
}

export type LoadHistoryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  load?: Prisma.LoadUpdateOneRequiredWithoutHistoryNestedInput
}

export type LoadHistoryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loadId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  loadId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryCreateManyLoadInput = {
  id?: string
  action: string
  description?: string | null
  changedBy: string
  createdAt?: Date | string
}

export type LoadHistoryUpdateWithoutLoadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLoadHistoryNestedInput
}

export type LoadHistoryUncheckedUpdateWithoutLoadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LoadHistoryUncheckedUpdateManyWithoutLoadInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LoadHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  loadId?: boolean
  action?: boolean
  description?: boolean
  changedBy?: boolean
  createdAt?: boolean
  load?: boolean | Prisma.LoadDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["loadHistory"]>



export type LoadHistorySelectScalar = {
  id?: boolean
  loadId?: boolean
  action?: boolean
  description?: boolean
  changedBy?: boolean
  createdAt?: boolean
}

export type LoadHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "loadId" | "action" | "description" | "changedBy" | "createdAt", ExtArgs["result"]["loadHistory"]>
export type LoadHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  load?: boolean | Prisma.LoadDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LoadHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LoadHistory"
  objects: {
    load: Prisma.$LoadPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    loadId: string
    action: string
    description: string | null
    changedBy: string
    createdAt: Date
  }, ExtArgs["result"]["loadHistory"]>
  composites: {}
}

export type LoadHistoryGetPayload<S extends boolean | null | undefined | LoadHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload, S>

export type LoadHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LoadHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LoadHistoryCountAggregateInputType | true
  }

export interface LoadHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LoadHistory'], meta: { name: 'LoadHistory' } }
  /**
   * Find zero or one LoadHistory that matches the filter.
   * @param {LoadHistoryFindUniqueArgs} args - Arguments to find a LoadHistory
   * @example
   * // Get one LoadHistory
   * const loadHistory = await prisma.loadHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LoadHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, LoadHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LoadHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LoadHistoryFindUniqueOrThrowArgs} args - Arguments to find a LoadHistory
   * @example
   * // Get one LoadHistory
   * const loadHistory = await prisma.loadHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LoadHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LoadHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoadHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryFindFirstArgs} args - Arguments to find a LoadHistory
   * @example
   * // Get one LoadHistory
   * const loadHistory = await prisma.loadHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LoadHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, LoadHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LoadHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryFindFirstOrThrowArgs} args - Arguments to find a LoadHistory
   * @example
   * // Get one LoadHistory
   * const loadHistory = await prisma.loadHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LoadHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LoadHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LoadHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LoadHistories
   * const loadHistories = await prisma.loadHistory.findMany()
   * 
   * // Get first 10 LoadHistories
   * const loadHistories = await prisma.loadHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const loadHistoryWithIdOnly = await prisma.loadHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LoadHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, LoadHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LoadHistory.
   * @param {LoadHistoryCreateArgs} args - Arguments to create a LoadHistory.
   * @example
   * // Create one LoadHistory
   * const LoadHistory = await prisma.loadHistory.create({
   *   data: {
   *     // ... data to create a LoadHistory
   *   }
   * })
   * 
   */
  create<T extends LoadHistoryCreateArgs>(args: Prisma.SelectSubset<T, LoadHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LoadHistories.
   * @param {LoadHistoryCreateManyArgs} args - Arguments to create many LoadHistories.
   * @example
   * // Create many LoadHistories
   * const loadHistory = await prisma.loadHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LoadHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, LoadHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a LoadHistory.
   * @param {LoadHistoryDeleteArgs} args - Arguments to delete one LoadHistory.
   * @example
   * // Delete one LoadHistory
   * const LoadHistory = await prisma.loadHistory.delete({
   *   where: {
   *     // ... filter to delete one LoadHistory
   *   }
   * })
   * 
   */
  delete<T extends LoadHistoryDeleteArgs>(args: Prisma.SelectSubset<T, LoadHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LoadHistory.
   * @param {LoadHistoryUpdateArgs} args - Arguments to update one LoadHistory.
   * @example
   * // Update one LoadHistory
   * const loadHistory = await prisma.loadHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LoadHistoryUpdateArgs>(args: Prisma.SelectSubset<T, LoadHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LoadHistories.
   * @param {LoadHistoryDeleteManyArgs} args - Arguments to filter LoadHistories to delete.
   * @example
   * // Delete a few LoadHistories
   * const { count } = await prisma.loadHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LoadHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, LoadHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LoadHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LoadHistories
   * const loadHistory = await prisma.loadHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LoadHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, LoadHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one LoadHistory.
   * @param {LoadHistoryUpsertArgs} args - Arguments to update or create a LoadHistory.
   * @example
   * // Update or create a LoadHistory
   * const loadHistory = await prisma.loadHistory.upsert({
   *   create: {
   *     // ... data to create a LoadHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LoadHistory we want to update
   *   }
   * })
   */
  upsert<T extends LoadHistoryUpsertArgs>(args: Prisma.SelectSubset<T, LoadHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__LoadHistoryClient<runtime.Types.Result.GetResult<Prisma.$LoadHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LoadHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryCountArgs} args - Arguments to filter LoadHistories to count.
   * @example
   * // Count the number of LoadHistories
   * const count = await prisma.loadHistory.count({
   *   where: {
   *     // ... the filter for the LoadHistories we want to count
   *   }
   * })
  **/
  count<T extends LoadHistoryCountArgs>(
    args?: Prisma.Subset<T, LoadHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LoadHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LoadHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LoadHistoryAggregateArgs>(args: Prisma.Subset<T, LoadHistoryAggregateArgs>): Prisma.PrismaPromise<GetLoadHistoryAggregateType<T>>

  /**
   * Group by LoadHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LoadHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LoadHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LoadHistoryGroupByArgs['orderBy'] }
      : { orderBy?: LoadHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LoadHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLoadHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LoadHistory model
 */
readonly fields: LoadHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LoadHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LoadHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  load<T extends Prisma.LoadDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.LoadDefaultArgs<ExtArgs>>): Prisma.Prisma__LoadClient<runtime.Types.Result.GetResult<Prisma.$LoadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LoadHistory model
 */
export interface LoadHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"LoadHistory", 'String'>
  readonly loadId: Prisma.FieldRef<"LoadHistory", 'String'>
  readonly action: Prisma.FieldRef<"LoadHistory", 'String'>
  readonly description: Prisma.FieldRef<"LoadHistory", 'String'>
  readonly changedBy: Prisma.FieldRef<"LoadHistory", 'String'>
  readonly createdAt: Prisma.FieldRef<"LoadHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LoadHistory findUnique
 */
export type LoadHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoadHistory to fetch.
   */
  where: Prisma.LoadHistoryWhereUniqueInput
}

/**
 * LoadHistory findUniqueOrThrow
 */
export type LoadHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoadHistory to fetch.
   */
  where: Prisma.LoadHistoryWhereUniqueInput
}

/**
 * LoadHistory findFirst
 */
export type LoadHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoadHistory to fetch.
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoadHistories to fetch.
   */
  orderBy?: Prisma.LoadHistoryOrderByWithRelationInput | Prisma.LoadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoadHistories.
   */
  cursor?: Prisma.LoadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoadHistories.
   */
  distinct?: Prisma.LoadHistoryScalarFieldEnum | Prisma.LoadHistoryScalarFieldEnum[]
}

/**
 * LoadHistory findFirstOrThrow
 */
export type LoadHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoadHistory to fetch.
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoadHistories to fetch.
   */
  orderBy?: Prisma.LoadHistoryOrderByWithRelationInput | Prisma.LoadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LoadHistories.
   */
  cursor?: Prisma.LoadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoadHistories.
   */
  distinct?: Prisma.LoadHistoryScalarFieldEnum | Prisma.LoadHistoryScalarFieldEnum[]
}

/**
 * LoadHistory findMany
 */
export type LoadHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter, which LoadHistories to fetch.
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LoadHistories to fetch.
   */
  orderBy?: Prisma.LoadHistoryOrderByWithRelationInput | Prisma.LoadHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LoadHistories.
   */
  cursor?: Prisma.LoadHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LoadHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LoadHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LoadHistories.
   */
  distinct?: Prisma.LoadHistoryScalarFieldEnum | Prisma.LoadHistoryScalarFieldEnum[]
}

/**
 * LoadHistory create
 */
export type LoadHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a LoadHistory.
   */
  data: Prisma.XOR<Prisma.LoadHistoryCreateInput, Prisma.LoadHistoryUncheckedCreateInput>
}

/**
 * LoadHistory createMany
 */
export type LoadHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LoadHistories.
   */
  data: Prisma.LoadHistoryCreateManyInput | Prisma.LoadHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LoadHistory update
 */
export type LoadHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a LoadHistory.
   */
  data: Prisma.XOR<Prisma.LoadHistoryUpdateInput, Prisma.LoadHistoryUncheckedUpdateInput>
  /**
   * Choose, which LoadHistory to update.
   */
  where: Prisma.LoadHistoryWhereUniqueInput
}

/**
 * LoadHistory updateMany
 */
export type LoadHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LoadHistories.
   */
  data: Prisma.XOR<Prisma.LoadHistoryUpdateManyMutationInput, Prisma.LoadHistoryUncheckedUpdateManyInput>
  /**
   * Filter which LoadHistories to update
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * Limit how many LoadHistories to update.
   */
  limit?: number
}

/**
 * LoadHistory upsert
 */
export type LoadHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the LoadHistory to update in case it exists.
   */
  where: Prisma.LoadHistoryWhereUniqueInput
  /**
   * In case the LoadHistory found by the `where` argument doesn't exist, create a new LoadHistory with this data.
   */
  create: Prisma.XOR<Prisma.LoadHistoryCreateInput, Prisma.LoadHistoryUncheckedCreateInput>
  /**
   * In case the LoadHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LoadHistoryUpdateInput, Prisma.LoadHistoryUncheckedUpdateInput>
}

/**
 * LoadHistory delete
 */
export type LoadHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
  /**
   * Filter which LoadHistory to delete.
   */
  where: Prisma.LoadHistoryWhereUniqueInput
}

/**
 * LoadHistory deleteMany
 */
export type LoadHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LoadHistories to delete
   */
  where?: Prisma.LoadHistoryWhereInput
  /**
   * Limit how many LoadHistories to delete.
   */
  limit?: number
}

/**
 * LoadHistory without action
 */
export type LoadHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LoadHistory
   */
  select?: Prisma.LoadHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LoadHistory
   */
  omit?: Prisma.LoadHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LoadHistoryInclude<ExtArgs> | null
}
