ALTER TABLE `OperationLog`
    MODIFY `module` ENUM(
        'USER_MANAGEMENT',
        'LOAD_MANAGEMENT',
        'CONTAINER_TYPE_MANAGEMENT',
        'COMPANY_MANAGEMENT',
        'VEHICLE_MANAGEMENT',
        'DRIVER_MANAGEMENT',
        'DROP_LOCATION_MANAGEMENT',
        'DATABASE_BACKUP'
    ) NOT NULL;
