ALTER TABLE `Load`
    ADD COLUMN `totalFee` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `gasFee` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `driverPay` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `otherFee` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN `otherFeeRemark` VARCHAR(200) NULL,
    ADD COLUMN `balanceFee` DECIMAL(10, 2) NOT NULL DEFAULT 0.00;
