
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Container: 'Container',
  Vehicle: 'Vehicle',
  Driver: 'Driver',
  DropPoint: 'DropPoint',
  Load: 'Load',
  LoadHistory: 'LoadHistory'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  parentId: 'parentId',
  company: 'company',
  phone: 'phone',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ContainerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  capacity: 'capacity',
  length: 'length',
  width: 'width',
  height: 'height',
  weight: 'weight',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContainerScalarFieldEnum = (typeof ContainerScalarFieldEnum)[keyof typeof ContainerScalarFieldEnum]


export const VehicleScalarFieldEnum = {
  id: 'id',
  licensePlate: 'licensePlate',
  type: 'type',
  brand: 'brand',
  model: 'model',
  year: 'year',
  vin: 'vin',
  registrationDate: 'registrationDate',
  insuranceExpireDate: 'insuranceExpireDate',
  maintenanceDate: 'maintenanceDate',
  status: 'status',
  owner: 'owner',
  phone: 'phone',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VehicleScalarFieldEnum = (typeof VehicleScalarFieldEnum)[keyof typeof VehicleScalarFieldEnum]


export const DriverScalarFieldEnum = {
  id: 'id',
  name: 'name',
  idCard: 'idCard',
  phone: 'phone',
  email: 'email',
  drivingLicense: 'drivingLicense',
  licenseExpireDate: 'licenseExpireDate',
  licenseType: 'licenseType',
  qualifications: 'qualifications',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  status: 'status',
  address: 'address',
  emergencyContact: 'emergencyContact',
  emergencyPhone: 'emergencyPhone',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DriverScalarFieldEnum = (typeof DriverScalarFieldEnum)[keyof typeof DriverScalarFieldEnum]


export const DropPointScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  province: 'province',
  city: 'city',
  district: 'district',
  address: 'address',
  latitude: 'latitude',
  longitude: 'longitude',
  contactPerson: 'contactPerson',
  contactPhone: 'contactPhone',
  workingHours: 'workingHours',
  type: 'type',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DropPointScalarFieldEnum = (typeof DropPointScalarFieldEnum)[keyof typeof DropPointScalarFieldEnum]


export const LoadScalarFieldEnum = {
  id: 'id',
  loadNumber: 'loadNumber',
  status: 'status',
  containerId: 'containerId',
  containerQuantity: 'containerQuantity',
  vehicleId: 'vehicleId',
  driverId: 'driverId',
  assistantDriverId: 'assistantDriverId',
  pickupPointId: 'pickupPointId',
  dropPointId: 'dropPointId',
  shippingCompany: 'shippingCompany',
  bookingReference: 'bookingReference',
  blNumber: 'blNumber',
  commodityType: 'commodityType',
  weight: 'weight',
  scheduledPickupDate: 'scheduledPickupDate',
  actualPickupDate: 'actualPickupDate',
  scheduledDeliveryDate: 'scheduledDeliveryDate',
  actualDeliveryDate: 'actualDeliveryDate',
  fee: 'fee',
  surcharge: 'surcharge',
  totalFee: 'totalFee',
  paymentStatus: 'paymentStatus',
  paymentDate: 'paymentDate',
  notes: 'notes',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LoadScalarFieldEnum = (typeof LoadScalarFieldEnum)[keyof typeof LoadScalarFieldEnum]


export const LoadHistoryScalarFieldEnum = {
  id: 'id',
  loadId: 'loadId',
  action: 'action',
  description: 'description',
  changedBy: 'changedBy',
  createdAt: 'createdAt'
} as const

export type LoadHistoryScalarFieldEnum = (typeof LoadHistoryScalarFieldEnum)[keyof typeof LoadHistoryScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  parentId: 'parentId',
  company: 'company',
  phone: 'phone'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const ContainerOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type ContainerOrderByRelevanceFieldEnum = (typeof ContainerOrderByRelevanceFieldEnum)[keyof typeof ContainerOrderByRelevanceFieldEnum]


export const VehicleOrderByRelevanceFieldEnum = {
  id: 'id',
  licensePlate: 'licensePlate',
  type: 'type',
  brand: 'brand',
  model: 'model',
  vin: 'vin',
  owner: 'owner',
  phone: 'phone',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type VehicleOrderByRelevanceFieldEnum = (typeof VehicleOrderByRelevanceFieldEnum)[keyof typeof VehicleOrderByRelevanceFieldEnum]


export const DriverOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  idCard: 'idCard',
  phone: 'phone',
  email: 'email',
  drivingLicense: 'drivingLicense',
  licenseType: 'licenseType',
  qualifications: 'qualifications',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  address: 'address',
  emergencyContact: 'emergencyContact',
  emergencyPhone: 'emergencyPhone',
  createdBy: 'createdBy'
} as const

export type DriverOrderByRelevanceFieldEnum = (typeof DriverOrderByRelevanceFieldEnum)[keyof typeof DriverOrderByRelevanceFieldEnum]


export const DropPointOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  province: 'province',
  city: 'city',
  district: 'district',
  address: 'address',
  contactPerson: 'contactPerson',
  contactPhone: 'contactPhone',
  workingHours: 'workingHours',
  type: 'type',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type DropPointOrderByRelevanceFieldEnum = (typeof DropPointOrderByRelevanceFieldEnum)[keyof typeof DropPointOrderByRelevanceFieldEnum]


export const LoadOrderByRelevanceFieldEnum = {
  id: 'id',
  loadNumber: 'loadNumber',
  containerId: 'containerId',
  vehicleId: 'vehicleId',
  driverId: 'driverId',
  assistantDriverId: 'assistantDriverId',
  pickupPointId: 'pickupPointId',
  dropPointId: 'dropPointId',
  shippingCompany: 'shippingCompany',
  bookingReference: 'bookingReference',
  blNumber: 'blNumber',
  commodityType: 'commodityType',
  notes: 'notes',
  createdBy: 'createdBy'
} as const

export type LoadOrderByRelevanceFieldEnum = (typeof LoadOrderByRelevanceFieldEnum)[keyof typeof LoadOrderByRelevanceFieldEnum]


export const LoadHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  loadId: 'loadId',
  action: 'action',
  description: 'description',
  changedBy: 'changedBy'
} as const

export type LoadHistoryOrderByRelevanceFieldEnum = (typeof LoadHistoryOrderByRelevanceFieldEnum)[keyof typeof LoadHistoryOrderByRelevanceFieldEnum]

