
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
export const prismaVersion: PrismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Container: 'Container',
  Vehicle: 'Vehicle',
  Driver: 'Driver',
  DropPoint: 'DropPoint',
  Load: 'Load',
  LoadHistory: 'LoadHistory'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "container" | "vehicle" | "driver" | "dropPoint" | "load" | "loadHistory"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Container: {
      payload: Prisma.$ContainerPayload<ExtArgs>
      fields: Prisma.ContainerFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ContainerFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ContainerFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        findFirst: {
          args: Prisma.ContainerFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ContainerFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        findMany: {
          args: Prisma.ContainerFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>[]
        }
        create: {
          args: Prisma.ContainerCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        createMany: {
          args: Prisma.ContainerCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ContainerDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        update: {
          args: Prisma.ContainerUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        deleteMany: {
          args: Prisma.ContainerDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ContainerUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ContainerUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContainerPayload>
        }
        aggregate: {
          args: Prisma.ContainerAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateContainer>
        }
        groupBy: {
          args: Prisma.ContainerGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContainerGroupByOutputType>[]
        }
        count: {
          args: Prisma.ContainerCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContainerCountAggregateOutputType> | number
        }
      }
    }
    Vehicle: {
      payload: Prisma.$VehiclePayload<ExtArgs>
      fields: Prisma.VehicleFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VehicleFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VehicleFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        findFirst: {
          args: Prisma.VehicleFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VehicleFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        findMany: {
          args: Prisma.VehicleFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>[]
        }
        create: {
          args: Prisma.VehicleCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        createMany: {
          args: Prisma.VehicleCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.VehicleDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        update: {
          args: Prisma.VehicleUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        deleteMany: {
          args: Prisma.VehicleDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VehicleUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.VehicleUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VehiclePayload>
        }
        aggregate: {
          args: Prisma.VehicleAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVehicle>
        }
        groupBy: {
          args: Prisma.VehicleGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VehicleGroupByOutputType>[]
        }
        count: {
          args: Prisma.VehicleCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VehicleCountAggregateOutputType> | number
        }
      }
    }
    Driver: {
      payload: Prisma.$DriverPayload<ExtArgs>
      fields: Prisma.DriverFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DriverFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DriverFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        findFirst: {
          args: Prisma.DriverFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DriverFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        findMany: {
          args: Prisma.DriverFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>[]
        }
        create: {
          args: Prisma.DriverCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        createMany: {
          args: Prisma.DriverCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.DriverDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        update: {
          args: Prisma.DriverUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        deleteMany: {
          args: Prisma.DriverDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DriverUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.DriverUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DriverPayload>
        }
        aggregate: {
          args: Prisma.DriverAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDriver>
        }
        groupBy: {
          args: Prisma.DriverGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DriverGroupByOutputType>[]
        }
        count: {
          args: Prisma.DriverCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DriverCountAggregateOutputType> | number
        }
      }
    }
    DropPoint: {
      payload: Prisma.$DropPointPayload<ExtArgs>
      fields: Prisma.DropPointFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DropPointFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DropPointFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        findFirst: {
          args: Prisma.DropPointFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DropPointFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        findMany: {
          args: Prisma.DropPointFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>[]
        }
        create: {
          args: Prisma.DropPointCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        createMany: {
          args: Prisma.DropPointCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.DropPointDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        update: {
          args: Prisma.DropPointUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        deleteMany: {
          args: Prisma.DropPointDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DropPointUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.DropPointUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DropPointPayload>
        }
        aggregate: {
          args: Prisma.DropPointAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDropPoint>
        }
        groupBy: {
          args: Prisma.DropPointGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DropPointGroupByOutputType>[]
        }
        count: {
          args: Prisma.DropPointCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DropPointCountAggregateOutputType> | number
        }
      }
    }
    Load: {
      payload: Prisma.$LoadPayload<ExtArgs>
      fields: Prisma.LoadFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LoadFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LoadFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        findFirst: {
          args: Prisma.LoadFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LoadFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        findMany: {
          args: Prisma.LoadFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>[]
        }
        create: {
          args: Prisma.LoadCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        createMany: {
          args: Prisma.LoadCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.LoadDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        update: {
          args: Prisma.LoadUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        deleteMany: {
          args: Prisma.LoadDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LoadUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.LoadUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadPayload>
        }
        aggregate: {
          args: Prisma.LoadAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLoad>
        }
        groupBy: {
          args: Prisma.LoadGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LoadGroupByOutputType>[]
        }
        count: {
          args: Prisma.LoadCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LoadCountAggregateOutputType> | number
        }
      }
    }
    LoadHistory: {
      payload: Prisma.$LoadHistoryPayload<ExtArgs>
      fields: Prisma.LoadHistoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LoadHistoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LoadHistoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        findFirst: {
          args: Prisma.LoadHistoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LoadHistoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        findMany: {
          args: Prisma.LoadHistoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>[]
        }
        create: {
          args: Prisma.LoadHistoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        createMany: {
          args: Prisma.LoadHistoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.LoadHistoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        update: {
          args: Prisma.LoadHistoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        deleteMany: {
          args: Prisma.LoadHistoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LoadHistoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.LoadHistoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LoadHistoryPayload>
        }
        aggregate: {
          args: Prisma.LoadHistoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLoadHistory>
        }
        groupBy: {
          args: Prisma.LoadHistoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LoadHistoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.LoadHistoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LoadHistoryCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  parentId: 'parentId',
  company: 'company',
  phone: 'phone',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ContainerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  capacity: 'capacity',
  length: 'length',
  width: 'width',
  height: 'height',
  weight: 'weight',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContainerScalarFieldEnum = (typeof ContainerScalarFieldEnum)[keyof typeof ContainerScalarFieldEnum]


export const VehicleScalarFieldEnum = {
  id: 'id',
  licensePlate: 'licensePlate',
  type: 'type',
  brand: 'brand',
  model: 'model',
  year: 'year',
  vin: 'vin',
  registrationDate: 'registrationDate',
  insuranceExpireDate: 'insuranceExpireDate',
  maintenanceDate: 'maintenanceDate',
  status: 'status',
  owner: 'owner',
  phone: 'phone',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VehicleScalarFieldEnum = (typeof VehicleScalarFieldEnum)[keyof typeof VehicleScalarFieldEnum]


export const DriverScalarFieldEnum = {
  id: 'id',
  name: 'name',
  idCard: 'idCard',
  phone: 'phone',
  email: 'email',
  drivingLicense: 'drivingLicense',
  licenseExpireDate: 'licenseExpireDate',
  licenseType: 'licenseType',
  qualifications: 'qualifications',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  status: 'status',
  address: 'address',
  emergencyContact: 'emergencyContact',
  emergencyPhone: 'emergencyPhone',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DriverScalarFieldEnum = (typeof DriverScalarFieldEnum)[keyof typeof DriverScalarFieldEnum]


export const DropPointScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  province: 'province',
  city: 'city',
  district: 'district',
  address: 'address',
  latitude: 'latitude',
  longitude: 'longitude',
  contactPerson: 'contactPerson',
  contactPhone: 'contactPhone',
  workingHours: 'workingHours',
  type: 'type',
  description: 'description',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DropPointScalarFieldEnum = (typeof DropPointScalarFieldEnum)[keyof typeof DropPointScalarFieldEnum]


export const LoadScalarFieldEnum = {
  id: 'id',
  loadNumber: 'loadNumber',
  status: 'status',
  containerId: 'containerId',
  containerQuantity: 'containerQuantity',
  vehicleId: 'vehicleId',
  driverId: 'driverId',
  assistantDriverId: 'assistantDriverId',
  pickupPointId: 'pickupPointId',
  dropPointId: 'dropPointId',
  shippingCompany: 'shippingCompany',
  bookingReference: 'bookingReference',
  blNumber: 'blNumber',
  commodityType: 'commodityType',
  weight: 'weight',
  scheduledPickupDate: 'scheduledPickupDate',
  actualPickupDate: 'actualPickupDate',
  scheduledDeliveryDate: 'scheduledDeliveryDate',
  actualDeliveryDate: 'actualDeliveryDate',
  fee: 'fee',
  surcharge: 'surcharge',
  totalFee: 'totalFee',
  paymentStatus: 'paymentStatus',
  paymentDate: 'paymentDate',
  notes: 'notes',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LoadScalarFieldEnum = (typeof LoadScalarFieldEnum)[keyof typeof LoadScalarFieldEnum]


export const LoadHistoryScalarFieldEnum = {
  id: 'id',
  loadId: 'loadId',
  action: 'action',
  description: 'description',
  changedBy: 'changedBy',
  createdAt: 'createdAt'
} as const

export type LoadHistoryScalarFieldEnum = (typeof LoadHistoryScalarFieldEnum)[keyof typeof LoadHistoryScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  parentId: 'parentId',
  company: 'company',
  phone: 'phone'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const ContainerOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type ContainerOrderByRelevanceFieldEnum = (typeof ContainerOrderByRelevanceFieldEnum)[keyof typeof ContainerOrderByRelevanceFieldEnum]


export const VehicleOrderByRelevanceFieldEnum = {
  id: 'id',
  licensePlate: 'licensePlate',
  type: 'type',
  brand: 'brand',
  model: 'model',
  vin: 'vin',
  owner: 'owner',
  phone: 'phone',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type VehicleOrderByRelevanceFieldEnum = (typeof VehicleOrderByRelevanceFieldEnum)[keyof typeof VehicleOrderByRelevanceFieldEnum]


export const DriverOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  idCard: 'idCard',
  phone: 'phone',
  email: 'email',
  drivingLicense: 'drivingLicense',
  licenseType: 'licenseType',
  qualifications: 'qualifications',
  bankAccount: 'bankAccount',
  bankName: 'bankName',
  address: 'address',
  emergencyContact: 'emergencyContact',
  emergencyPhone: 'emergencyPhone',
  createdBy: 'createdBy'
} as const

export type DriverOrderByRelevanceFieldEnum = (typeof DriverOrderByRelevanceFieldEnum)[keyof typeof DriverOrderByRelevanceFieldEnum]


export const DropPointOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  province: 'province',
  city: 'city',
  district: 'district',
  address: 'address',
  contactPerson: 'contactPerson',
  contactPhone: 'contactPhone',
  workingHours: 'workingHours',
  type: 'type',
  description: 'description',
  createdBy: 'createdBy'
} as const

export type DropPointOrderByRelevanceFieldEnum = (typeof DropPointOrderByRelevanceFieldEnum)[keyof typeof DropPointOrderByRelevanceFieldEnum]


export const LoadOrderByRelevanceFieldEnum = {
  id: 'id',
  loadNumber: 'loadNumber',
  containerId: 'containerId',
  vehicleId: 'vehicleId',
  driverId: 'driverId',
  assistantDriverId: 'assistantDriverId',
  pickupPointId: 'pickupPointId',
  dropPointId: 'dropPointId',
  shippingCompany: 'shippingCompany',
  bookingReference: 'bookingReference',
  blNumber: 'blNumber',
  commodityType: 'commodityType',
  notes: 'notes',
  createdBy: 'createdBy'
} as const

export type LoadOrderByRelevanceFieldEnum = (typeof LoadOrderByRelevanceFieldEnum)[keyof typeof LoadOrderByRelevanceFieldEnum]


export const LoadHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  loadId: 'loadId',
  action: 'action',
  description: 'description',
  changedBy: 'changedBy'
} as const

export type LoadHistoryOrderByRelevanceFieldEnum = (typeof LoadHistoryOrderByRelevanceFieldEnum)[keyof typeof LoadHistoryOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'VehicleStatus'
 */
export type EnumVehicleStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'VehicleStatus'>
    


/**
 * Reference to a field of type 'DriverStatus'
 */
export type EnumDriverStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DriverStatus'>
    


/**
 * Reference to a field of type 'LoadStatus'
 */
export type EnumLoadStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'LoadStatus'>
    


/**
 * Reference to a field of type 'PaymentStatus'
 */
export type EnumPaymentStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PaymentStatus'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  container?: Prisma.ContainerOmit
  vehicle?: Prisma.VehicleOmit
  driver?: Prisma.DriverOmit
  dropPoint?: Prisma.DropPointOmit
  load?: Prisma.LoadOmit
  loadHistory?: Prisma.LoadHistoryOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

